url: "https://napalm-automation.net"
name: Napalm Network Automation
description: Open Source Network Automation
repository: "napalm-automation/napalm-automation.github.io"
permalink: /:title/

# Site Author
author:
  name             : "Napalm Automation"
  github           : napalm-automation
  twitter          : napalm_auto



paginate: 10 # amount of posts to show
paginate_path: /blog/page:num/

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

build:
  prod: true
  analytics: UA-102455886-1


encoding: "utf-8"

defaults:
  # _posts
  - scope:
      path: "_posts/announcements"
      type: posts
    values:
      layout: post
      read_time: false
      comments: true

  - scope:
      path: "_posts/dbarrosop"
      type: posts
    values:
      author: dbarrosop
      layout: post
      author_profile: true
      read_time: false
      comments: true
      share: true

  - scope:
      path: "_posts/mirceaulinic"
      type: posts
    values:
      author: mirceaulinic
      layout: post
      author_profile: true
      read_time: false
      comments: true
      share: true

  - scope:
      path: ""
      type: profiles
    values:
      layout: profile


collections:
  profiles:
    output: true
    permalink: /:collection/:path/


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Reading Files
include:
  - _pages

exclude:
  - .bundle
  - Gemfile
  - vendor
  - tests/
  - Makefile
  - README.md

sass:
  sass_dir: _sass
  style: compressed
